project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  back-to-top-navigation: true
  favicon: favicon.png
  title: "Jairon K. Ojeda S."
  site-url: "https://jaironkevin.github.io/"
  navbar:
    background: "#536878"
    left:
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publicaciones
      - href: software/index.qmd
        text: Shiny apps
      - href: portafolio/index.qmd
        text: Portafolio
      - href: servicios/index.qmd
        text: Servicios
  page-footer:
    left: "Â© 2025 Jairon Ojeda. Website built with Quarto in RStudio"
    right:
      - icon: github
        href: https://github.com/jaironkevin
      - icon: linkedin
        href: www.linkedin.com/in/jairon-ojeda
    background: "#536878"

date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    code-copy: true
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
execute:
  freeze: auto
